spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    
mybatis: 
  mapper-locations:
  - classpath:com/example/demo/mapper/*.xml
  type-aliases-package: com.example.demo.entity
    